### ISSUE TITLE
Issue with a JSON string with a list in a list causing a parser failure.

### ISSUE THREAD

**Issue by deepgrant** [VerizonDigital/json_parser#2]
This is the JSON text:
```json
{"path": "/foo/bar", "cmd": "GET", "data": {"command": "insert", "payload": {"table_name": "table1", "columns": ["id", "column1"], "thedata": [["1", "2"], ["2", "4"], ["3", "8"], ["4", "8"], ["5", "10"]]}}}
```
This is the subbuffer:

`$10 = {static npos = 18446744073709551615, m_p = 0x7ffff00109f8 "{\"path\": \"/fabric/topology\", \"cmd\": \"GET\", \"data\": {\"command\": \"insert\", \"payload\": {\"table_name\": \"table1a\", \"columns\": [\"id\", \"column1\"], \"thedata\": [[\"1\", \"2\"], [\"2\", \"4\"], [\"3\", \"8\"], [\"4\", \"8\"], "..., m_len = 216}`

This is the error reported:

`/json_parser/include/json_parser.h:309: object::parse, does not start with ", val: '["2", "4"], ["3", "8"], ["4", "8"], ["5", "10"]]}}}
', prev: 'insert", "payload": {"table_name": "table1a", "columns": ["id", "column1"], "thedata": [["1", "2"], '
`

From stepping the code I think the formatting causes the parser to skip over the second [ at the start of the list for 'thedata'.

Changing the string to be indented with spaces to split up the back to back [[ gets around the problem.

```json
{
    "path" : "/foo/bar",
    "cmd" : "GET",
    "data" : {
        "command" : "insert",
        "payload" : {
            "table_name" : "table1",
            "columns" : [
                "id",
                "column1"
            ],
            "thedata" : [
                [
                    "1",
                    "2"
                ],
                [
                    "2",
                    "4"
                ],
                [
                    "3",
                    "8"
                ],
                [
                    "4",
                    "8"
                ],
                [
                    "5",
                    "10"
                ]
            ]
        }
    }
}```

**Comment by dsyeager** [comment]
Grant, thx for the report, I'll take a look this morning

**Comment by deepgrant** [comment]
Thank you Sir.

**Comment by deepgrant** [comment]
Much appreciated. Thank you for the quick response.

**Comment by dsyeager** [comment]
Should work for you now. Added a test case with your string and validated that it now parses correctly. Thanks for the error report.

**Comment by deepgrant** [comment]
No problem. Thank you so much.
