### ISSUE TITLE
Memory Leak in json_parser.h

### ISSUE THREAD

**Issue by adoszpy** [VerizonDigital/json_parser#3]
Hi,

with libFuzzer I could identify a memory leak issue in json_parser.h.
The payload which was generated by the fuzzer is the following: {""{}""{
This payload can cause the memory leak and there is not any WARN or ERROR although this is not a valid input.
Here is the report of the LeakSanitizer:
==3905==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 104 byte(s) in 1 object(s) allocated from:
…
    #1 0x4efc37 in json::value::parse(subbuffer&) /json_parser/include/json_parser.h:639:38
…

**Comment by dsyeager** [comment]
looking now

**Comment by dsyeager** [comment]
The object::parse method was not validating that the passed in json was valid.
It is now checking for:
- empty keys
- missing colons
- missing commas
- missing closing }
